- tests/cpp_api_tests/rocAL_basic_test/CMakeLists.txt
- tests/cpp_api_tests/rocAL_dataloader/CMakeLists.txt
- tests/cpp_api_tests/rocAL_dataloader_mt/CMakeLists.txt
- tests/cpp_api_tests/rocAL_dataloader_tf/CMakeLists.txt
- tests/cpp_api_tests/rocAL_performance_tests/CMakeLists.txt
- tests/cpp_api_tests/rocAL_performance_tests_with_depth/CMakeLists.txt
- tests/cpp_api_tests/rocAL_unittests/CMakeLists.txt
- tests/cpp_api_tests/rocAL_video_unittests/CMakeLists.txt
> Test - Add ROCm Iclude Path

- README.md
- docker/README.md
- docker/rocal-on-rhel-09.dockerfile
- docker/rocal-on-ubuntu-20-with-pytorch-with-mesa.dockerfile
- docker/rocal-on-ubuntu-20.dockerfile
- docker/rocal-on-ubuntu-22.dockerfile
- docker/rocal-with-pytorch.dockerfile
- docs/README.md
- docs/user_guide/ch1.md
- docs/user_guide/ch2.md
- docs/user_guide/ch3.md
- docs/user_guide/ch4.md
- docs/user_guide/ch5.md
- docs/user_guide/ch6.md
- rocAL_pybind/examples/README.md
- rocAL_pybind/examples/tf_petsTrainingExample/README.md
- rocAL_pybind/setup.py
- tests/cpp_api_tests/rocAL_unittests/README.md
- tests/cpp_api_tests/rocAL_video_unittests/README.md
Update links to repositories to reflect new organization.
> Update links in README files

- cmake/FindTurboJpeg.cmake
- rocAL/CMakeLists.txt
> TurboJpeg Cmake Fix

- cmake/FindTurboJpeg.cmake
- docs/README.md
- rocAL/CMakeLists.txt
- rocAL/include/decoders/libjpeg/libjpeg_utils.h
- rocAL/source/decoders/libjpeg/libjpeg_extra.cpp
It was causing build issues with recent releases of turbo-jpeg library
> remove jpegint.h dependency from rocAL

- docs/how-to/framework.rst
- docs/how-to/using-with-python.rst
- docs/index.rst
- docs/sphinx/_toc.yml.in
This PR fixes broken links and sphinx errors in docs.
> Docs: fix broken links

- docs/how-to/framework.rst
- docs/how-to/using-with-python.rst
- docs/index.rst
- docs/sphinx/_toc.yml.in
This PR adds the link fixes added to develop and docs/6.1.0 into docs/6.1.1
> docs: Cherry-pick broken link fixes into 6.1.1

- rocAL-setup.py
This is required on Ubuntu24 and to resolve the [ticket](https://ontrack-internal.amd.com/browse/SWDEV-459846)
> Setup.py - add wheel installation

- rocAL_pybind/amd/rocal/plugin/generic.py
- rocAL_pybind/amd/rocal/plugin/tf.py
Adding fixes for importing cupy in generic.py and tf.py
> Cupy import fix

- tests/cpp_api/unit_tests/testAllScripts.sh
- tests/cpp_api/unit_tests/unit_tests.cpp
- tests/python_api/readers_test_file.sh
- tests/python_api/unit_test.py
- tests/python_api/unit_tests.sh
- New rocal data is generated and a PR has been created - https://github.com/ROCm/MIVisionX-data/pull/13
- This PR contains contains path changes needed for the new rocal data
> Unit Test changes for new rocal data

- CHANGELOG.md
- CMakeLists.txt
- README.md
- rocAL-setup.py
* PIP install packages
* OS identified
> Setup - Updates

- README.md
> Readme - Updates

- CHANGELOG.md
- CMakeLists.txt
- README.md
- cmake/FindTurboJpeg.cmake
- rocAL-setup.py
updates
* Setup
```
rocAL Dependencies Installed with rocAL-setup.py on Linux-6.5.0-41-generic-x86_64-with-centos-7.9.2009-Core-redhat-7
```
* Build
+ Package
```
-- AMD ROCm rocAL RunTime Package --  rpp, mivisionx
-- AMD ROCm rocAL Dev Package --  rocal, rpp-devel, mivisionx-devel, lmdb-devel, protobuf-devel
-- AMD ROCm rocAL RunTime Package --  rpp, mivisionx
-- AMD ROCm rocAL Dev Package --  rocal, rpp-dev, mivisionx-dev, liblmdb-dev, libprotobuf-dev
```
+ Build
```
bash-4.2# make
[  1%] Built target rocAL_hip
[ 97%] Built target rocal
[100%] Built target rocal_pybind
bash-4.2# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7" …
```
> CentOS 7 - Support

- CHANGELOG.md
- README.md
- rocAL-setup.py
Support rocAL setup on SLES 15 SP5
> SLES 15 SP5 - support updates

- CHANGELOG.md
- README.md
- rocAL-setup.py
> Setup - SLES 15 SP5 Updates

- rocAL-setup.py
> Setup: RHEL - fix FFMPEG

- docs/README.md
This PR updates the REAME for audio augmentations added.
> Audio readme update

- .jenkins/common.groovy
For elevated permissions in SLES pipeline
> CI: Run python setup as sudo

- rocAL/source/api/rocal_api.cpp
- rocAL_pybind/amd/rocal/pipeline.py
Fixes an issue where negative device IDs were passed to pipeline creation
> Adding fix for negative device_id in pipeline creation

- rocAL/source/readers/file_source_reader.cpp
This PR fixes the image unit tests
> Fix Last Batch Policy PR

- CHANGELOG.md
- CMakeLists.txt
- README.md
- rocAL_pybind/getrocALwheelname.py
- rocAL_pybind/setup.py
* Changelog updates and cleanup
* Fix for rocBlas addition into rocAL - https://github.com/ROCm/rocAL/commit/faeae0aa02071c39e3a84813ff195eb19b989e9f
* Version updates
> CHANGELOG Updates

- rocAL/source/augmentations/node_ssd_random_crop.cpp
- rocAL/source/decoders/image/turbo_jpeg_decoder.cpp
- rocAL/source/meta_data/coco_meta_data_reader.cpp
- Resolve warnings wrt uninitialized variables in rocAL
> Fix rocAL Warnings for Ubuntu 24

- CHANGELOG.md
- CMakeLists.txt
- README.md
- docs/install/install.rst
- rocAL-setup.py
- rocAL/CMakeLists.txt
- rocAL/rocAL_hip/CMakeLists.txt
- rocAL_pybind/CMakeLists.txt
- tests/cpp_api/CMakeLists.txt
- tests/cpp_api/audio_tests/CMakeLists.txt
- tests/cpp_api/basic_test/CMakeLists.txt
- tests/cpp_api/dataloader/CMakeLists.txt
- tests/cpp_api/dataloader_multithread/CMakeLists.txt
- tests/cpp_api/dataloader_tf/CMakeLists.txt
- tests/cpp_api/external_source/CMakeLists.txt
- tests/cpp_api/image_augmentation/CMakeLists.txt
- tests/cpp_api/performance_tests/CMakeLists.txt
- tests/cpp_api/performance_tests_with_depth/CMakeLists.txt
- tests/cpp_api/unit_tests/CMakeLists.txt
- tests/cpp_api/video_tests/CMakeLists.txt
- tests/pybind/CMakeLists.txt
* CMake Version update
* CXX Compiler set to use AMD Clang++
> CMakeLists - Compiler & CMake Version Updates

- docs/index.rst
- docs/reference/rocAL-and-RNNT.rst
- docs/sphinx/_toc.yml.in
Added the RNNT topic and also fixed the ordering of the landing page table while I was at it.
> commit of the RNNT topic

- rocAL-setup.py
Setup missing audio deps for RPM based OS
> Setup - Audio RPM Req

- tests/cpp_api/unit_tests/README.md
- tests/python_api/README.md
Fixes various typos and inconsistencies + removes erroneous link
> Test - Fix README inconsistencies

- tests/cpp_api/CMakeLists.txt
@fiona-gladwin please check if the parameters are correct for the rocdecode video reader.
@kiritigowda adding this test only for rocm6.5 and above. Please check if it looks ok
```
lakshmi@kapu:~/work/lk/rocAL/build$ make test
Running tests...
Test project /home/lakshmi/work/lk/rocAL/build
Start  1: basic_test_cpu
1/15 Test  #1: basic_test_cpu .....................   Passed    2.42 sec
Start  2: basic_test_gpu
2/15 Test  #2: basic_test_gpu .....................   Passed    0.80 sec
Start  3: basic_test_gray
3/15 Test  #3: basic_test_gray ....................   Passed    0.69 sec
Start  4: basic_test_rgb
4/15 Test  #4: basic_test_rgb .....................   Passed    0.82 sec
Start  5: dataloader_multithread_cpu
5/15 Test  #5: dataloader_multithread_cpu .........   Passed    3.47 sec
Start …
```
> CTest - Adding ctest for rocdecode integration

- CMakeLists.txt
Support Debian
```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
> CMakeLists - Support Debian OS

- .jenkins/common.groovy
> Jenkins - Code Coverage

- README.md
- rocAL-setup.py
Add support to install deps on Oracle OS
> Setup - Support Oracle OS
