- rocAL/source/augmentations/geometry_augmentations/node_crop.cpp
Without including vx_ext_amd.h header file, the rocal build fails with the following error on the develop branch: 
```
rocAL/source/augmentations/geometry_augmentations/node_crop.cpp:111:20: error: ‘VX_MEMORY_TYPE_HIP’ was not declared in this scope; did you mean ‘VX_MEMORY_TYPE_HOST’?
111 |         mem_type = VX_MEMORY_TYPE_HIP;
|                    ^~~~~~~~~~~~~~~~~~
|                    VX_MEMORY_TYPE_HOST
```
> CPU Build Fix

- rocAL/source/pipeline/tensor.cpp
Including cl.h file in the cpu backend fails when opencl is not installed. 
Added a fix to address this issue.
> Include Fix for CPU Backend

- apps/image_augmentation/image_augmentation.cpp
- docs/examples/image_processing/decoder.py
- docs/examples/image_processing/decoder_examples.ipynb
- docs/examples/image_processing/inference_pipeline.py
- rocAL-setup.py
- rocAL/CMakeLists.txt
- rocAL/include/decoders/image/fused_crop_decoder.h
- rocAL/include/decoders/image/turbo_jpeg_decoder.h
- rocAL/include/decoders/libjpeg/libjpeg_extra.h
- rocAL/include/decoders/libjpeg/libjpeg_utils.h
- rocAL/include/loaders/image/image_read_and_decode.h
- rocAL/source/decoders/image/fused_crop_decoder.cpp
- rocAL/source/decoders/image/turbo_jpeg_decoder.cpp
- rocAL/source/decoders/libjpeg/libjpeg_extra.cpp
- rocAL_pybind/setup.py
Removes private branch for turbojpeg.
Upgraded turbojpeg to public branch 3.0.1.
Need to re-run setup script for the changes to take effect
> turbojpeg library update for rocAL

- CMakeLists.txt
- cmake/FindMIVisionX.cmake
- rocAL_pybind/CMakeLists.txt
Remove unnecessary variable : MIVisionX_LIBRARIES_DIRS
Update rocAL CMake to exclude rocAL_pybind subdirectory if manually turned off
> CMakeLists.txt update to remove unnecessary variable - develop

- rocAL_pybind/amd/rocal/pipeline.py
Commenting out `get_one_hot_encoded_labels` from pipeline.py.
This function `b.getOneHotEncodedLabels` is not defined in rocal_pybind.cpp.
Also removes cupy requirement from Pipeline.
@swetha097 We need to discuss this offline
> removing undefined functions

- LICENSE.txt
- docs/examples.rst
- docs/how-to/architecture.rst
- docs/how-to/framework.rst
- docs/how-to/index.rst
- docs/how-to/overview.rst
- docs/how-to/using-with-cpp.rst
- docs/how-to/using-with-python.rst
- docs/index.rst
- docs/install/install.rst
- docs/license.md
- docs/license.rst
- docs/sphinx/_toc.yml.in
Docs changes from master to develop
> Docs - Cherry Pick

- docker/rocal-on-ubuntu-20-with-pytorch-with-mesa.dockerfile
- docker/rocal-on-ubuntu-20.dockerfile
- docker/rocal-on-ubuntu-22.dockerfile
- docker/rocal-with-pytorch.dockerfile
- rocAL-setup.py
CuPy, turboJPEG and rpp updates
> Setup & Docker updates

- rocAL/include/parameters/parameter.h
- rocAL/include/parameters/parameter_factory.h
- rocAL/include/parameters/parameter_random.h
- rocAL/include/parameters/parameter_simple.h
- rocAL/include/parameters/parameter_vx.h
- rocAL/source/parameters/parameter_factory.cpp
- rocAL Parameter creation and updation moved from parameter_vx.h to respective param classes (parameter_random.h & parameter_simple.h) so that the rocAL random / simple parameter's instance is created only once and updated when renew is called from master_graph
- Added seed vector used for instantiating random parameter with different seed
> rocAL - Parameter changes

- rocAL/include/pipeline/master_graph.h
- This PR fixes errors while building rocAL without ffmpeg
- Added missing ROCAL_VIDEO flag for add_node of video loaders
> rocAL Fix video flag

- rocAL_pybind/amd/rocal/plugin/generic.py
- rocAL_pybind/amd/rocal/plugin/tf.py
- tests/python_api/decoder.py
- tests/python_api/tf_classification_reader.py
- tests/python_api/tf_detection_reader.py
- tests/python_api/unit_test.py
Adding a try...except block to check for CuPy. Upgrading to rocm6.2 fails to build CuPy. This PR makes the generic and tf plugins fall back and use CPU is CuPy is not available. Tested decoder.py, tf_classification and tf_detection and unit_test.sh
> Bug Fix - Tests fall back to CPU if CuPy unavailable

- docs/how-to/framework.rst
- docs/how-to/using-with-python.rst
Fixed one more link in #142 while merging into docs/6.1.0. Add to develop as well.
> Add 6.1.0 link fix to develop

- CMakeLists.txt
- README.md
- rocAL/CMakeLists.txt
- Introduce CMake flag to enable Audio support
- Add changes to enable Audio features only for ROCm version > 6.2
> Introduce flag in CMake to enable Audio support

- .github/workflows/linting.yml
rocm-docs-core moved from RadeonOpenCompute to ROCm
> Fix org used for linting workflow by rocm-docs-core

- docs/user_guide/ch3.md
docs.amd.com > rocm.docs.amd.com
> Update documentation link

- tests/cpp_api/unit_tests/testAllScripts.sh
- Commented out test cases for four augmentations which throws errors in C++ unit tests
> Fix errors in unit tests

- docs/how-to/framework.rst
- docs/how-to/overview.rst
- docs/user_guide/ch1.md
This fixes three bad links to the examples directory or one of its subdirectories.
> Docs - Fix a few erroneous links to the examples directory

- docs/examples/notebooks/spectrogram.ipynb
- Adding an example notebook for audio processing with spectrogram augmentation
> Spectrogram example notebook

- docs/examples/pytorch/imagenet_training/README.md
- docs/examples/pytorch/imagenet_training/imagenet_training.py
- Adding support for calculating the avg per-epoch dataloader time and images per second in the pytorch imagenet training
example
. The user can choose the dataloader for calculating the IPS and dataloader time - the example runs the dataloader for 3 epochs without training.
> Update pytorch training example

- CHANGELOG.md
Updated the changelog file for 6.2.1 so that it reflects what is in the 6.2.1 Release Notes and conforms to the documentation standards. 
The changelog for subsequent versions should conform to this standard.
> Updated 6.2.1 changelog so that it reflects the 6.2.1 RN

- rocAL/include/readers/file_source_reader.h
- Remove redundant private variables, already present in Reader base class
> Fix File Source reader

- cmake/FindTurboJpeg.cmake
- Removes the check for LIBJPEG_LIBRARIES and LIBJPEG_INCLUDE_DIRS from FindTurboJPEG.cmake
- JPEG includes are provided by turbojpeg package so its sufficient to only check for turbojpeg library
- Fixes #287
> Remove libjpeg check in CMake
